name: Publish release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Install dependencies
        run: npm ci

      - name: Extract tag version number
        id: get_version
        run: echo "version-without-v=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: Run build
        env:
          MODULE_VERSION: ${{ steps.get_version.outputs.version-without-v }}
          GH_PROJECT: ${{ github.repository }}
          GH_TAG: ${{ github.event.release.tag_name }}
        run: npm run build

      - name: Create zip archive
        working-directory: dist
        run: zip -r ./module.zip module.json style.css scripts/ templates/ languages/

      - name: Update release with files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./dist/module.json, ./dist/module.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
